
version: 0.0
os: linux
files:             
  - source: /
    destination: /home/ec2-user
hooks:
  BeforeInstall:
    - location: ./codedeploy/beforeInstall.sh
      timeout: 300
      runas: centos
  ApplicationStart:
    - location: ./codedeploy/applicationStart.sh
      timeout: 300
      runas: centos
  ApplicationStop:
    - location: ./codedeploy/applicationStop.sh
      timeout: 300
      runas: centos