# Generated by Django 3.2.5 on 2022-02-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=32, null=True)),
                ('last_name', models.CharField(blank=True, max_length=32, null=True)),
                ('password', models.CharField(blank=True, max_length=90, null=True)),
                ('username', models.EmailField(blank=True, max_length=254, null=True)),
                ('account_created', models.DateTimeField(auto_now=True, null=True)),
                ('account_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
