# Generated by Django 3.2.12 on 2022-03-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
