# Generated by Django 3.2.5 on 2022-02-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0002_userregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='account_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
