# Generated by Django 3.2.5 on 2022-02-12 20:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0003_alter_userregister_account_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
