# Generated by Django 3.2.5 on 2022-02-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0004_auto_20220212_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='username',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
