# Generated by Django 3.2.5 on 2022-02-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0005_alter_userregister_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='username',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
