# Generated by Django 3.2.5 on 2022-02-13 00:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0007_alter_userregister_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='account_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
