# Generated by Django 3.2.5 on 2022-02-13 01:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0008_alter_userregister_account_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='account_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
