# Generated by Django 3.2.5 on 2022-02-13 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0009_alter_userregister_account_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='username',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
