# Generated by Django 3.2.5 on 2022-02-13 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0010_alter_userregister_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregister',
            name='token',
        ),
    ]
