name: Python Django unit test

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: Huawei12#$
          MYSQL_DATABASE: login_signup
        ports: ['3306:3306']

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.7
      # - name: Start Mysql
      #   run: |
      #     mysqld --install
      #     net start mysql
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run migrations
        run: |
          ls -la
          cd DjangoAPI
          python manage.py migrate
      - name: Run tests
        run: |
          cd DjangoAPI
          python manage.py test
